name: Test cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

      # Note that this step is also triggered near the end to build the cache.
    - name: Cache LaTeX
      id: cache-nix
      uses: actions/cache@v2.1.0
      with:
        # See https://stackoverflow.com/questions/59269850.
        path: |
            ~/nix/store
            ~/nix/bin
        # Using number to enforce fresh cache.
        key: ${{ runner.os }}-10

    - name: Install Nix
      uses: cachix/install-nix-action@v10
      with:
          nix_path: nixpkgs=channel:nixos-unstable

    - name: Install LaTeX
      env:
          CACHE_HIT: ${{ steps.cache-nix.outputs.cache-hit }}
      run: |
        NIX_BIN=/nix/var/nix/profiles/per-user/runner/profile/bin
        NIX_STORE=/nix/store
        if [[ "$CACHE_HIT" != 'true' ]]; then
          nix-env --install --file latex.nix
          mkdir -p ~/nix/store
          mkdir -p ~/nix/bin
          sudo cp --force --recursive $NIX_STORE/* ~/nix/store/
          sudo cp --verbose --force --recursive $NIX_BIN/* ~/nix/bin/
        else
          sudo mkdir -p $NIX_STORE
          sudo mkdir -p $NIX_BIN
          sudo cp --force --recursive ~/nix/store/* $NIX_STORE/
          sudo cp --force --recursive ~/nix/bin/* $NIX_BIN/
        fi

    - name: Check existence of pdflatex
      run: pdflatex --version

