name: Test cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check cache for Nix and use if found
      id: cache-nix
      uses: actions/cache@v2
      with:
        # See https://stackoverflow.com/questions/59269850.
        path: |
            ~/nix/store
            ~/nix/bin
        key: ${{ runner.os }}-nix6

    - name: Install Nix if not cached
      if: steps.cache-nix.outputs.cache-hit != 'true'
      uses: cachix/install-nix-action@v10
      with:
          nix_path: nixpkgs=channel:nixos-unstable

    - name: Install LaTeX if not cached
      env:
          CACHE_HIT: ${{ steps.cache-nix.outputs.cache-hit }}
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          nix-env --install --file latex.nix
          mkdir -p ~/nix/store
          mkdir -p ~/nix/bin
          sudo cp --force --recursive /nix/store/* ~/nix/store/
          sudo cp --verbose --force --recursive /nix/var/nix/profiles/per-user/runner/profile/bin/* ~/nix/bin/
          which xdotool
        else
          sudo cp --force --recursive ~/nix/store/* /nix/store/
          sudo cp --force --recursive ~/nix/bin/* /nix/var/nix/profiles/per-user/runner/profile/bin/
          which xdotool
        fi

    - run: which xdotool
